apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: p1
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource             # Specify the type of metric
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 1
